export * from './MainPage'
export * from './CatalogPage'
export * from './OrderFormPage'
export * from './AdminPages'
export * from './ProfilePages'
export * from './FavoritePage'
export * from './LoginPage'
export * from './RegisterPage'